language: python

env:
  global:
    - CODECOV_TOKEN='6cad1bd5-233c-47bc-aecc-2021b2d6cdda'

python:
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - coverage run -m unittest discover
  - coverage xml
after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml || echo "Codecov did not collect coverage reports"