# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import crud_client_pb2 as crud__client__pb2


class CrudClientServiceStub(object):
    """The insert client service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.insert = channel.unary_unary(
                '/client.CrudClientService/insert',
                request_serializer=crud__client__pb2.Client.SerializeToString,
                response_deserializer=crud__client__pb2.Client.FromString,
                )
        self.update = channel.unary_unary(
                '/client.CrudClientService/update',
                request_serializer=crud__client__pb2.Client.SerializeToString,
                response_deserializer=crud__client__pb2.Client.FromString,
                )
        self.search_by_id = channel.unary_unary(
                '/client.CrudClientService/search_by_id',
                request_serializer=crud__client__pb2.SearchClientRequest.SerializeToString,
                response_deserializer=crud__client__pb2.Client.FromString,
                )
        self.delete_by_id = channel.unary_unary(
                '/client.CrudClientService/delete_by_id',
                request_serializer=crud__client__pb2.SearchClientRequest.SerializeToString,
                response_deserializer=crud__client__pb2.Client.FromString,
                )


class CrudClientServiceServicer(object):
    """The insert client service definition.
    """

    def insert(self, request, context):
        """insert new client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """update  client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def search_by_id(self, request, context):
        """search client by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_by_id(self, request, context):
        """delete Client by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrudClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'insert': grpc.unary_unary_rpc_method_handler(
                    servicer.insert,
                    request_deserializer=crud__client__pb2.Client.FromString,
                    response_serializer=crud__client__pb2.Client.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=crud__client__pb2.Client.FromString,
                    response_serializer=crud__client__pb2.Client.SerializeToString,
            ),
            'search_by_id': grpc.unary_unary_rpc_method_handler(
                    servicer.search_by_id,
                    request_deserializer=crud__client__pb2.SearchClientRequest.FromString,
                    response_serializer=crud__client__pb2.Client.SerializeToString,
            ),
            'delete_by_id': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_by_id,
                    request_deserializer=crud__client__pb2.SearchClientRequest.FromString,
                    response_serializer=crud__client__pb2.Client.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'client.CrudClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CrudClientService(object):
    """The insert client service definition.
    """

    @staticmethod
    def insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/client.CrudClientService/insert',
            crud__client__pb2.Client.SerializeToString,
            crud__client__pb2.Client.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/client.CrudClientService/update',
            crud__client__pb2.Client.SerializeToString,
            crud__client__pb2.Client.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def search_by_id(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/client.CrudClientService/search_by_id',
            crud__client__pb2.SearchClientRequest.SerializeToString,
            crud__client__pb2.Client.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete_by_id(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/client.CrudClientService/delete_by_id',
            crud__client__pb2.SearchClientRequest.SerializeToString,
            crud__client__pb2.Client.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
