# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import insert_client_pb2 as insert__client__pb2


class InsertClientServiceStub(object):
    """The insert client service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.insertNewClient = channel.unary_unary(
            '/client.InsertClientService/insertNewClient',
            request_serializer=insert__client__pb2.InsertClientRequest.SerializeToString,
            response_deserializer=insert__client__pb2.InsertNewClientResponse.FromString,
        )


class InsertClientServiceServicer(object):
    """The insert client service definition.
    """

    def insertNewClient(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InsertClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'insertNewClient': grpc.unary_unary_rpc_method_handler(
            servicer.insertNewClient,
            request_deserializer=insert__client__pb2.InsertClientRequest.FromString,
            response_serializer=insert__client__pb2.InsertNewClientResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'client.InsertClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class InsertClientService(object):
    """The insert client service definition.
    """

    @staticmethod
    def insertNewClient(request,
                        target,
                        options=(),
                        channel_credentials=None,
                        call_credentials=None,
                        insecure=False,
                        compression=None,
                        wait_for_ready=None,
                        timeout=None,
                        metadata=None):
        return grpc.experimental.unary_unary(request, target, '/client.InsertClientService/insertNewClient',
                                             insert__client__pb2.InsertClientRequest.SerializeToString,
                                             insert__client__pb2.InsertNewClientResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
