# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: insert_client.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='insert_client.proto',
  package='client',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13insert_client.proto\x12\x06\x63lient\"R\n\x13InsertClientRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x63pf\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12\x14\n\x0c\x66\x61voriteFood\x18\x04 \x01(\t\")\n\x17InsertNewClientResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2h\n\x13InsertClientService\x12Q\n\x0finsertNewClient\x12\x1b.client.InsertClientRequest\x1a\x1f.client.InsertNewClientResponse\"\x00\x62\x06proto3'
)




_INSERTCLIENTREQUEST = _descriptor.Descriptor(
  name='InsertClientRequest',
  full_name='client.InsertClientRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='client.InsertClientRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cpf', full_name='client.InsertClientRequest.cpf', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='client.InsertClientRequest.id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='favoriteFood', full_name='client.InsertClientRequest.favoriteFood', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=113,
)


_INSERTNEWCLIENTRESPONSE = _descriptor.Descriptor(
  name='InsertNewClientResponse',
  full_name='client.InsertNewClientResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='client.InsertNewClientResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=156,
)

DESCRIPTOR.message_types_by_name['InsertClientRequest'] = _INSERTCLIENTREQUEST
DESCRIPTOR.message_types_by_name['InsertNewClientResponse'] = _INSERTNEWCLIENTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InsertClientRequest = _reflection.GeneratedProtocolMessageType('InsertClientRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSERTCLIENTREQUEST,
  '__module__' : 'insert_client_pb2'
  # @@protoc_insertion_point(class_scope:client.InsertClientRequest)
  })
_sym_db.RegisterMessage(InsertClientRequest)

InsertNewClientResponse = _reflection.GeneratedProtocolMessageType('InsertNewClientResponse', (_message.Message,), {
  'DESCRIPTOR' : _INSERTNEWCLIENTRESPONSE,
  '__module__' : 'insert_client_pb2'
  # @@protoc_insertion_point(class_scope:client.InsertNewClientResponse)
  })
_sym_db.RegisterMessage(InsertNewClientResponse)



_INSERTCLIENTSERVICE = _descriptor.ServiceDescriptor(
  name='InsertClientService',
  full_name='client.InsertClientService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=158,
  serialized_end=262,
  methods=[
  _descriptor.MethodDescriptor(
    name='insertNewClient',
    full_name='client.InsertClientService.insertNewClient',
    index=0,
    containing_service=None,
    input_type=_INSERTCLIENTREQUEST,
    output_type=_INSERTNEWCLIENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INSERTCLIENTSERVICE)

DESCRIPTOR.services_by_name['InsertClientService'] = _INSERTCLIENTSERVICE

# @@protoc_insertion_point(module_scope)
